### ISSUE TITLE
JINJA_EXTENSIONS change

### ISSUE THREAD

**Issue by dglava** [AlexJF/pelican-advthumbnailer#5]
I'm getting a `CRITICAL: KeyError: 'JINJA_EXTENSIONS'` when running Pelican with the advthumbnailer plugin.
I assume it has to do with [this](https://blog.getpelican.com/category/news.html) change in recent Pelican versions:

> JINJA_EXTENSIONS has been replaced by the JINJA_ENVIRONMENT setting. Any plugins that refer to the former setting will need to be updated. Refer to the corresponding entry in the Settings documentation for more information.

**Comment by AlexJF** [comment]
Thanks for the report. Latest version (0.7.0 - 63c27535) should have fixed this. Sorry for taking so long :)

**Comment by dglava** [comment]
Thanks for fixing this.
